# Generated by Django 5.1 on 2024-08-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedback',
            name='question',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='question',
            field=models.ManyToManyField(to='myapp.questions'),
        ),
    ]
